// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-T2cH9flX2Yb2_0__FN4CZYJI3T9My_A',
    appId: '1:411594668654:web:ca36bdfe6f9045c98b447f',
    messagingSenderId: '411594668654',
    projectId: 'fitbot-992f8',
    authDomain: 'fitbot-992f8.firebaseapp.com',
    storageBucket: 'fitbot-992f8.firebasestorage.app',
    measurementId: 'G-HXHEHWL79E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYqiGfoR5R98fmVa1eYuA4pL_Wa9lN1ec',
    appId: '1:411594668654:android:5c26af2cb25dd6f88b447f',
    messagingSenderId: '411594668654',
    projectId: 'fitbot-992f8',
    storageBucket: 'fitbot-992f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTrR1UBuDfb9dJzOhqbJ4x8PD-p2UwKzs',
    appId: '1:411594668654:ios:330f7f332dabbe2f8b447f',
    messagingSenderId: '411594668654',
    projectId: 'fitbot-992f8',
    storageBucket: 'fitbot-992f8.firebasestorage.app',
    iosBundleId: 'com.example.fitbotapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTrR1UBuDfb9dJzOhqbJ4x8PD-p2UwKzs',
    appId: '1:411594668654:ios:330f7f332dabbe2f8b447f',
    messagingSenderId: '411594668654',
    projectId: 'fitbot-992f8',
    storageBucket: 'fitbot-992f8.firebasestorage.app',
    iosBundleId: 'com.example.fitbotapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-T2cH9flX2Yb2_0__FN4CZYJI3T9My_A',
    appId: '1:411594668654:web:0ed52ca814c11f698b447f',
    messagingSenderId: '411594668654',
    projectId: 'fitbot-992f8',
    authDomain: 'fitbot-992f8.firebaseapp.com',
    storageBucket: 'fitbot-992f8.firebasestorage.app',
    measurementId: 'G-WX69VNPMHH',
  );

}